// <auto-generated />
using System;
using DevCommander.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevCommander.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714144834_AgentCostEntries")]
    partial class AgentCostEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DevCommander.Domain.Entities.AgentCostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LlmCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MissionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("AgentRole", "At");

                    b.ToTable("AgentCostEntries");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CommandIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DecidedByChatId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MissionId", "SquadId", "TaskId", "Attempt", "CommandIndex", "CommandHash")
                        .IsUnique();

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccountedCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BudgetUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhaseSummariesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogicalKey")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.Repo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultRuntime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatedOpsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifyCommandsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Repos");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.Squad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCommit")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCommittedSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastGuidance")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastPid")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pushed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorktreePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MissionId", "RepoId")
                        .IsUnique();

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.SquadEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SquadId", "At");

                    b.ToTable("SquadEvents");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaselineCommit")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedCommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorSignature")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhaseSummary")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("SquadId", "Phase", "Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.TelegramUpdate", b =>
                {
                    b.Property<long>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("UpdateId");

                    b.HasIndex("ChatId", "UpdateId");

                    b.HasIndex("State", "ReceivedAt");

                    b.ToTable("TelegramUpdates");
                });

            modelBuilder.Entity("NovaCore.Agents.Persistence.EntityFramework.AgentMemoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_key");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ScopeKey", "Idx")
                        .IsUnique();

                    b.ToTable("agent_memories", (string)null);
                });

            modelBuilder.Entity("NovaCore.Agents.Persistence.EntityFramework.AgentMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PartsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parts_json");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("ToolCallId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<long>("TurnNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turn_number");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "TurnNumber")
                        .IsUnique();

                    b.ToTable("agent_messages", (string)null);
                });

            modelBuilder.Entity("NovaCore.Agents.Persistence.EntityFramework.AgentSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("SummaryText")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary_text");

                    b.Property<long?>("SummaryUpToTurn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("summary_up_to_turn");

                    b.Property<DateTimeOffset?>("SummaryUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LastActivityAt");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.Squad", b =>
                {
                    b.HasOne("DevCommander.Domain.Entities.Mission", "Mission")
                        .WithMany("Squads")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.SquadEvent", b =>
                {
                    b.HasOne("DevCommander.Domain.Entities.Squad", "Squad")
                        .WithMany("Events")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("DevCommander.Domain.Entities.Mission", "Mission")
                        .WithMany("Tasks")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevCommander.Domain.Entities.Squad", "Squad")
                        .WithMany("Tasks")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("NovaCore.Agents.Persistence.EntityFramework.AgentMessage", b =>
                {
                    b.HasOne("NovaCore.Agents.Persistence.EntityFramework.AgentSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.Mission", b =>
                {
                    b.Navigation("Squads");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DevCommander.Domain.Entities.Squad", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("NovaCore.Agents.Persistence.EntityFramework.AgentSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
